### PR TITLE
Add linePadding test as applied to ruby text

### PR DESCRIPTION
**Pull request by palemieux**

### CODE REVIEW

**Review by nigelmegitt — APPROVED** [review]
I believe this is a correct rendering for this test content.

**Comment by cconcolato** [comment]
Several questions:
- why would the background not apply to the annotation?
- why use lineHeight at all? Given that the value in lineHeight and padding are similar 125 and .25, it could be confused that they need to have related values. Also the change of unit % vs c makes it hard to understand.
- couldn't the test explicitly set the ruby size? The `.25em` value is unclear.

**Comment by palemieux** [comment]
@cconcolato The file is one of the one provided at https://github.com/w3c/imsc-tests/pull/104 . I just assume not modify it unless broken.

**Comment by nigelmegitt** [comment]
> why would the background not apply to the annotation?

@cconcolato I spent some time this morning trying to answer this question. I ended up making a [codepen](https://codepen.io/nigelmegitt/pen/abKEMVR) to convince myself that this isn't quite as strange a thing as it seems at first. Essentially, the padding rectangle of an inline area does not seem to extend to encompass all the padding rectangles of its child elements, even with spans. Ruby is no different here. If you want background to be painted on ruby text, the choices seem to be:

1. Set `tts:backgroundColor` on the ruby text span.
2. Set `ebutts:fillLineGap="true"` on the parent p so that the background of the whole line is extended to include all the content.
3. Some other thing I haven't thought of, or thought through properly, like maybe creating an inline block wrapper element.

See also https://github.com/sandflow/imscJS/pull/238#issuecomment-1321862821

**Comment by nigelmegitt** [comment]
@cconcolato oh, one other thing: I think the point was made that it's the TTML2 semantics that matter here, not the CSS semantics, but as far as I can tell TTML2 does not go into any greater detail about this question.

**Pull request merged**
