### PR TITLE
Improve tts:textEmphasis tests

### PR DESCRIPTION
**Pull request by palemieux**
The current tests do not work if the implementation ignores "after" and "before" values of `tts:textEmphasis`, and defaults to the initial value of `"outside"`.

Edit: Corrected `"around"` to `"outside"`.

### CODE REVIEW

**Comment by palemieux** [comment]
@nigelmegitt As it stands, `"before"` and `"after"` values are tested on two different lines within a single `p`, essentially emulating the value of `"around`" such that an implementation that only understands "around" would still pass the test by ignoring the `"before"` and `"after"` values.

**Comment by nigelmegitt** [comment]
There is no position value of `textEmphasis` that is `around` - I think maybe you mean `outside` @palemieux ? That is the default if the position component is omitted.

Anyway I think I've managed to understand the problem here. Please could you confirm I've understood correctly?

Before, each `p` had two lines separated by a `br`. In each `p` the first line had `before` emphasis, and the second line had `after` emphasis. The correct behaviour would be indistinguishable from an identical file where all the emphasis positions are `outside`, so the test did not distinguish between an implementation that correctly supports `before` and `after`, and another that only supports `outside` and ignores the position component.

The changes here put each line in a different `p` so there's only one line area. That means the behaviour of an implementation that does not support `before` is now (still) indistinguishable from one that supports `outside`.

To resolve that, the `before` tests should have an additional line prepended at the beginning of the `p` they occur in. The `after` tests would fail if they were treated as `outside` without any further changes.

Does that make sense?

**Comment by skynavga** [comment]
@nigelmegitt keep in mind the following language under `<annotation-position>` (emphasis added)

>If an implementation does not recognize or otherwise distinguish an annotation position value, then it must be interpreted as if a position of before were specified; as such, **an implementation that supports text annotation marks must minimally support the before value**.

**Comment by nigelmegitt** [comment]
@skynavga Thanks for that, I hadn't spotted it. That means that the minimally-required support differs from the initial value. I imagine that would surprise people, but not in a good way.

**Comment by nigelmegitt** [comment]
As Chair, I'd like to point out that my https://github.com/w3c/imsc-tests/pull/87#issuecomment-516918768 was off-topic and should be raised on TTML2 if it's a problem.

**Comment by palemieux** [comment]
> The correct behaviour would be indistinguishable from an identical file where all the emphasis positions are outside

Yes.

**Comment by palemieux** [comment]
@nigelmegitt Please review the updated tests.

**Pull request merged**
